---
title: "Thesis - First Census"
author: "Mauricio Marcos Fajgenbaun"
date: "8/7/2021"
output: html_document
---



```{r}
##################################################################################
# Simulation experiment to compare the performance of Census EB and ELL estimators
# of poverty indicators, when the survey is not a subset of the census.

##################################################################################


#########################################
# Generation of a population
#########################################

rm(list=ls())
#setwd("C:/Isa/AdvisorWB/AdvisorBootstrapPaulACorral/Simulations/NewModelBasedSimulations")

# Setting of sizes and initialization of vectors

library(nlme)
N<-20000        # Number of population units
D<-80           # Number of areas
Nd<-rep(250,D)      # Number of population units in each area
p<-3            # Number of auxiliary variables (intercept+2 dummies)
p1<-rep(0,D)       # Probability of the first category of X1
x1<-NULL       # X1 values
p2<-rep(0,D)       # Probability of the second category of X2
x2<-NULL       # X2 values
#
## Generation of auxiliary variables (2 dummies with probability of 1 given by p1 and p2)
#
for (d in 1:D){
    p1[d]<-0.3+0.5*d/D
    p2[d]<-0.2
    x1<-c(x1,rbinom(Nd[d],size=1,prob=p1[d]))
    x2<-c(x2,rbinom(Nd[d],size=1,prob=p2[d]))
}
#
write.table(data.frame(x1,x2),"AuxVarD80.txt")
x<-read.table("AuxVarD80.txt",header=TRUE)
x1<-x[,1]
x2<-x[,2]
```

```{r}
#########################################
# Extraction of a stratified SRS
#########################################

# Sample sizes

nd<-Nd/5
n<-sum(nd)

# Extraction of sample indexes

samp<-NULL
sumNd<-0

for (d in 1:D){
   samp<-c(samp,sample((sumNd+1):(sumNd+Nd[d]),size=nd[d],replace=FALSE))
    sumNd<-sumNd+Nd[d]
}
write.table(samp,"SampleD80.txt")

sample<-read.table("SampleD80.txt",header=TRUE)
samp<-sample[,1]
```


```{r}
# Sample elements of aux. variables
x1s<-x1[samp]
x2s<-x2[samp]
Xs<-cbind(rep(1,n),x1s,x2s)

# Non-Sample elements of aux. variables
x1r<-x1[-samp]
x2r<-x2[-samp]
Xr<-cbind(rep(1,N-n),x1r,x2r)

# Non-sample sizes of the areas
rd<-Nd-nd

# Area/province indicator

area<-NULL
for(d in 1:D){
  area<-c(area,rep(d,nd[d]))
}

```

```{r}
#########################################
# Monte Carlo simulations
#########################################

# Parameter values

beta<-c(3,0.03,-0.04)
sigmae2<-(0.5)^2
sigmau2<-(0.15)^2
sigmau2/(sigmau2+sigmae2/nd[1])
z<-12    # Poverty line: It is approximately 0.6 Median(E) for the whole population

gamma=sigmau2/(sigmau2+sigmae2/nd[1]) #=0.71
# We should try with different values for gamma, such as gamma=0.3,0.6

# Monte Carlo iterations

#nMC<-10000
nMC<-100

# Initialization of matrices that will contain poverty proportions and gaps
# Each column is for the D area quantities for each Monte Carlo simulation

propMC<-matrix(0,nr=D,nc=nMC)
gapMC<-matrix(0,nr=D,nc=nMC)
propsMC<-matrix(0,nr=D,nc=nMC)
gapsMC<-matrix(0,nr=D,nc=nMC)
propfinMC<-matrix(0,nr=D,nc=nMC)
gapfinMC<-matrix(0,nr=D,nc=nMC)
propfinMC.ELL<-matrix(0,nr=D,nc=nMC)
gapfinMC.ELL<-matrix(0,nr=D,nc=nMC)
MSEpropMC.ELL<-matrix(0,nr=D,nc=nMC)
MSEgapMC.ELL<-matrix(0,nr=D,nc=nMC)

time1<-Sys.time()
time1

for (i in 1:nMC){  # Start of Monte Carlo cycle: Generation of populations and calculation of EBPs
  
  print(i)
  print(Sys.time())
  
  sumNd<-0
  sumnd<-0
  y<-NULL
  ys<-NULL
  
  # Generation of population values of the response, area by area
  # Calculation of true area poverty proportions and gaps
  
  for (d in 1:D){
    
    ed<-rnorm(Nd[d],0,sqrt(sigmae2))
    ud<-rnorm(1,0,sqrt(sigmau2))
    Xd<-cbind(rep(1,Nd[d]),x1[(sumNd+1):(sumNd+Nd[d])],x2[(sumNd+1):(sumNd+Nd[d])])
    
    mud<-Xd%*%beta
    yd<-mud+ud+ed
    Ed<-exp(yd)
    y<-c(y,yd)
    
    # I save them in the columns of a matrix
    propMC[d,i]<-mean(Ed<z)
    gapMC[d,i]<-mean((Ed<z)*(z-Ed)/z)
    
    # Generate sample values
    
    Xsd<-Xs[(sumnd+1):(sumnd+nd[d]),]
    musd<-Xsd%*%beta
    esd<-rnorm(nd[d],0,sqrt(sigmae2))
    ysd<-musd+ud+esd
    ys<-c(ys,ysd)
    
    sumNd<-sumNd+Nd[d]
    sumnd<-sumnd+nd[d]
  }
  
  E<-exp(y)       # People earnings
  
  # National poverty line
  # 0.6*median(E) # Poverty line
  # Resultado: 20.256
  
  # 100*mean(E<z)     # Population poverty incidence: Debería estar alrededor de un 15%
  # Resultado: 15.585
  # 100*mean((E<z)*(z-E)/z)   # Population poverty gap
  # Resultado: 3.437
  # data.frame(prop*100,gap*100)
  
  # Sample data 
  
  Es<-exp(ys)
  
  # Non-Sample data vectors and matrices
  
  yr<-y[-samp]
  
  # Sample poverty proportions and gaps at national level
  #100*mean(Es<z)
  #100*mean((Es<z)*(z-Es[1:n])/z)
  
  # Sample poverty proportions and gaps for the areas
  
  sumnd<-0
  
  for (d in 1:D){
    
    Esd<-Es[(sumnd+1):(sumnd+nd[d])]
    
    # I save them in the columns of a matrix
    propsMC[d,i]<-mean(Esd<z)
    gapsMC[d,i]<-mean((Esd<z)*(z-Esd)/z)
    
    sumnd<-sumnd+nd[d]
    
  }
  
  #data.frame(prop*100,props*100,gap*100,gaps*100)
  
  # Fitting of nested-error model to sample data
  
  fit<-lme(ys~x1s+x2s,random=~1|area,method="REML")
  Xs<-model.matrix(fit)
  betaest<-fixed.effects(fit)
  upred<-random.effects(fit)
  sigmae2est<-fit$sigma^2    # Varianza residual
  sigmau2est<-as.numeric(VarCorr(fit)[1,1]) # Matriz de covarianzas de las componentes aleatorias del modelo

  ############################################################
  # Generation of census values and calculation of Census 
  # EB and ELL poverty proportions and gaps for the areas
  ############################################################
  
  L<-50
  propsum<-rep(0,D)
  gapsum<-rep(0,D)
  propsum.ELL<-rep(0,D)
  gapsum.ELL<-rep(0,D)
  sumSqprop<-rep(0,D)
  sumSqgap<-rep(0,D)
  
  for (ell in 1:L){   ### Start of generations
    
    sumNd<-0
    
    for (d in 1:D){
      
      # Generation of census values from the distrib. given the sample data (Census EB prediction)
      
      Xd<-cbind(rep(1,Nd[d]),x1[(sumNd+1):(sumNd+Nd[d])],x2[(sumNd+1):(sumNd+Nd[d])])
      mudpred<-Xd%*%matrix(betaest,nr=p,nc=1)+upred[d,1]
      
      gammad<-sigmau2est/(sigmau2est+sigmae2est/nd[d])
      sigmav2<-sigmau2est*(1-gammad)
      vd<-rnorm(1,0,sqrt(sigmav2))
      ed<-rnorm(Nd[d],0,sqrt(sigmae2est))
      
      ydnew<-mudpred+vd+ed
      Ednew<-exp(ydnew)
      
      # EB predictors of poverty measures for each generation
      
      propsum[d]<-propsum[d]+mean(Ednew<z)
      gapsum[d]<-gapsum[d]+mean((Ednew<z)*(z-Ednew)/z)
      
      # Generation of population values of y from the fitted model
      # (ELL method with clusters = areas), using parametric bootstrap
      # and without heteroscedasticity
      
      ed.ELL<-ed
      ud.ELL<-rnorm(1,0,sqrt(sigmau2est))
      
      mud.ELL<-Xd%*%matrix(betaest,nr=p,nc=1)
      yd.ELL<-mud.ELL+ud.ELL+ed.ELL
      Ed.ELL<-exp(yd.ELL)
      
      # ELL predictors of poverty measures for each generation
      
      propsum.ELL[d]<-propsum.ELL[d]+mean(Ed.ELL<z)
      gapsum.ELL[d]<-gapsum.ELL[d]+mean((Ed.ELL<z)*(z-Ed.ELL)/z)
      
      # For the calculation of ELL estimator of MSE
      
      sumSqprop[d]<-sumSqprop[d]+(mean(Ed.ELL<z))^2
      sumSqgap[d]<-sumSqgap[d]+(mean((Ed.ELL<z)*(z-Ed.ELL)/z))^2
      
      sumNd<-sumNd+Nd[d]
      
    }
    
  }  # End of generations
  
  # EB predictors of poverty measures
  
  propfin<-propsum/L
  gapfin<-gapsum/L
  
  # ELL predictors of poverty measures and ELL mean squared error
  
  propfin.ELL<-propsum.ELL/L
  gapfin.ELL<-gapsum.ELL/L
  
  MSEpropMC.ELL[,i]<-sumSqprop/L-propfin.ELL^2
  MSEgapMC.ELL[,i]<-sumSqgap/L-gapfin.ELL^2
  
  #data.frame(prop,propfin,propfin.ELL,gap,gapfin,gapfin.ELL)
  
  # I save predictor values for each Monte Carlo simulation
  # in the columns of a matrix
  
  propfinMC[,i]<-propfin
  gapfinMC[,i]<-gapfin
  propfinMC.ELL[,i]<-propfin.ELL
  gapfinMC.ELL[,i]<-gapfin.ELL
  
  ###########  ###########  ###########  ###########
  # New EB using only data from the sample
  ###########  ###########  ###########  ###########
  
  # Amplify the sample by the relative weight of each observation
  
rel.we <- unique(Nd/nd)
x1s_rep <- rep(x1s,each=rel.we)
x2s_rep <- rep(x2s,each=rel.we)
X_rep<-cbind(rep(1,N),x1s_rep,x2s_rep)

write.table(data.frame(x1s_rep,x2s_rep),"AuxVarD80_rep.txt")
X_rep <-read.table("AuxVarD80_rep.txt",header=TRUE)
x1s_rep<-X_rep[,1]
x2s_rep<-X_rep[,2]

y_rep<-NULL
ys_rep<-NULL

  for (d in 1:D){
    
    ed_rep<-rnorm(Nd[d],0,sqrt(sigmae2))
    ud_rep<-rnorm(1,0,sqrt(sigmau2))
    Xd_rep<-cbind(rep(1,Nd[d]),x1s_rep[(sumNd+1):(sumNd+Nd[d])],x2s_rep[(sumNd+1):(sumNd+Nd[d])])
    
    mud_rep<-Xd_rep%*%beta
    yd_rep<-mud_rep+ud_rep+ed_rep
    Ed_rep<-exp(yd_rep)
    y_rep<-c(y_rep,yd_rep)
    
    # I save them in the columns of a matrix
    propMC_rep<-matrix(0,nr=D,nc=nMC)
    gapMC_rep<-matrix(0,nr=D,nc=nMC)
    propMC_rep[d,i]<-mean(Ed_rep<z)
    gapMC_rep[d,i]<-mean((Ed_rep<z)*(z-Ed_rep)/z)
    
    sumNd<-sumNd+Nd[d]
    sumnd<-sumnd+nd[d]
  }
  
  
}   # End of Monte Carlo simulations

time2 <- Sys.time()
print(difftime(time2,time1,units="mins"))

  propsum<-rep(0,D)
  gapsum<-rep(0,D)
  
  for (ell in 1:L){   ### Start of generations
    
    sumNd<-0
    
    for (d in 1:D){
      
      # Generation of census values from the distrib. given the sample data (Census EB prediction)
      
      Xd<-cbind(rep(1,Nd[d]),x1[(sumNd+1):(sumNd+Nd[d])],x2[(sumNd+1):(sumNd+Nd[d])])
      mudpred<-Xd%*%matrix(betaest,nr=p,nc=1)+upred[d,1]
      
      gammad<-sigmau2est/(sigmau2est+sigmae2est/nd[d])
      sigmav2<-sigmau2est*(1-gammad)
      vd<-rnorm(1,0,sqrt(sigmav2))
      ed<-rnorm(Nd[d],0,sqrt(sigmae2est))
      
      ydnew<-mudpred+vd+ed
      Ednew<-exp(ydnew)
      
      # EB predictors of poverty measures for each generation
      
      propsum[d]<-propsum[d]+mean(Ednew<z)
      gapsum[d]<-gapsum[d]+mean((Ednew<z)*(z-Ednew)/z)
      


#####################################################################

EmpiricalMSEpropPre<-rep(0,D)
EmpiricalMSEgapPre<-rep(0,D)
EmpiricalMSEpropPre.ELL<-rep(0,D)
EmpiricalMSEgapPre.ELL<-rep(0,D)
MSEpropMCr.ELL<-rep(0,D)
MSEgapMCr.ELL<-rep(0,D)

for (d in 1:D){
  EmpiricalMSEpropPre[d]<-mean((propfinMC[d,]-propMC[d,])^2)
  EmpiricalMSEgapPre[d]<-mean((gapfinMC[d,]-gapMC[d,])^2)
  EmpiricalMSEpropPre.ELL[d]<-mean((propfinMC.ELL[d,]-propMC[d,])^2)
  EmpiricalMSEgapPre.ELL[d]<-mean((gapfinMC.ELL[d,]-gapMC[d,])^2)
  MSEpropMCr.ELL[d]<-mean(MSEpropMC.ELL[d,])
  MSEgapMCr.ELL[d]<-mean(MSEgapMC.ELL[d,])
}

EmpiricalMSEPre<-data.frame(EmpiricalMSEpropPre,EmpiricalMSEgapPre,EmpiricalMSEpropPre.ELL,EmpiricalMSEgapPre.ELL,MSEpropMCr.ELL,MSEgapMCr.ELL)
write.table(EmpiricalMSEPre,"EmpiricalD80MC10000_Modified.txt",row.names=F)
```

